name: ebai
description: "The ebai  bidding platform"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

# ---- Pakages ---- #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  connectivity_plus: ^5.0.1
  lottie: ^3.3.1
  flutter_dotenv: ^5.2.1
  socket_io_client: ^3.1.2
  timeago: ^3.6.0
  shared_preferences: ^2.2.3

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  #State Managemens
  get: ^4.6.5
  get_storage: ^2.1.1

  # Producct Specific
  readmore: ^2.2.0
  carousel_slider: ^5.0.0

# ---- ./ Pakages end ---- #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # ---- Local Assets ---- #
  assets:
    - .env
    - assets/images/animations/
    - assets/images/onboarding/
    - assets/logos/
    - assets/icons/brands/
    - assets/images/banner/
    - assets/images/products/
    - assets/images/user/

  # ---- Local Assets ---- #

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
    #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
